'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Easier_Data_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property icon_16_colour2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_16_colour2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_character() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_character", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_collapse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_collapse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_delete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_delete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_expand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_expand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_free() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_free", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_mirror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_mirror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_paste_cool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_paste_cool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_quit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_quit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_recent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_recent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property icon_red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_save_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_save_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_select_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_select_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_splitH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_splitH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property indention() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indention", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instruction_function() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instruction_function", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manual_bookmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manual_bookmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;frame&gt;	 $  %FRAMENAME%
        '''	pic: $
        '''	centerx: $ 
        '''	centery: $
        '''	state: $  wait: $  next: $  hit_Uj: $ %others%
        '''%BODIES%
        '''%ITRS%
        '''%WPOINT%
        '''%BPOINT%
        '''%CPOINT%
        '''%OPOINT%
        '''%othersPoints%
        '''&lt;frame_end&gt;
        '''[][][]
        '''   bdy:
        '''      kind: $  x: $  y: $  w: $  h: $ %others%
        '''   bdy_end:
        '''[][][]
        '''   itr:
        '''      kind: $  x: $  y: $  w: $  h: $  
        '''      catchingact: $ $  caughtact: $ $  %others%
        '''   itr_end:
        '''[][][]
        '''   bpoint: x: $  y: $  %others% bpoint_end:
        '''[][][]
        '''   wpoint: kind: $  x: $  y: $  weaponact: $  attacking [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property reformatting_example() As String
            Get
                Return ResourceManager.GetString("reformatting_example", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;frame&gt; $ %FRAMENAME%
        '''   pic: $  state: $  wait: $  next: $  dvx: $  dvy: $  dvz: $  centerx: $  centery: $  %others%
        '''%OPOINT%
        '''%CPOINT%
        '''%BPOINT%
        '''%WPOINT%
        '''%ITRS%
        '''%BODIES%
        '''%othersPoints%
        '''&lt;frame_end&gt;
        '''[][][]
        '''   bdy:
        '''      kind: $  x: $  y: $  w: $  h: $ %others%
        '''   bdy_end:
        '''[][][]
        '''   itr:
        '''      kind: $  x: $  y: $  w: $  h: $  
        '''      catchingact: $ $  caughtact: $ $ %others%
        '''   itr_end:
        '''[][][]
        '''   bpoint:
        '''      x: $  y: $ %others%
        '''   bpoint_end:
        '''[][][]
        '''   wpoint:
        '''      kind: $  x: $  y:  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property reformatting_reset() As String
            Get
                Return ResourceManager.GetString("reformatting_reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;SyntaxDefinition name=&quot;LF2-Data&quot; extensions=&quot;.dat&quot;&gt;
        '''  &lt;Default forecol=&quot;Black&quot; backcol=&quot;White&quot; /&gt;
        '''  &lt;Regex name=&quot;CommentOut&quot; forecol=&quot;DimGray&quot; pattern=&quot;#.*&quot; /&gt;
        '''  &lt;Regex name=&quot;NameTag&quot; forecol=&quot;DimGray&quot; pattern=&quot;(?&amp;lt;=name:\s+)[^\n\r\s]+&quot; /&gt;
        '''  &lt;Regex name=&quot;File&quot; forecol=&quot;#FF008E61&quot; pattern=&quot;((?&amp;lt;=\s+|^)[A-Za-z_\-\/\\0-9]+)\.(?=.*[a-zA-Z])[^\s]{2,4}&quot; /&gt;
        '''  &lt;Regex name=&quot;BitmapFile&quot; forecol=&quot;DarkRed&quot; pattern=&quot;file\((?=\s*\d+\s*\-\s*\d+\s*\):)|(?&amp;lt;=file\(\s*\d+\s*\-\s*\d+\s*)\):&quot; /&gt;
        '''  &lt;Regex name=&quot;Fil [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property syntax() As String
            Get
                Return ResourceManager.GetString("syntax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;SyntaxDefinition name=&quot;LF2-Data&quot; extensions=&quot;.dat&quot;&gt;
        '''  &lt;Default forecol=&quot;Black&quot; backcol=&quot;White&quot; /&gt;
        '''  &lt;Regex name=&quot;CommentOut&quot; forecol=&quot;DimGray&quot; pattern=&quot;#.*&quot; /&gt;
        '''  &lt;Regex name=&quot;File&quot; forecol=&quot;#FF008E61&quot; pattern=&quot;((?&amp;lt;=\s+|^)[A-Za-z_\-\/\\0-9]+)\.(?=.*[a-zA-Z])[^\s]{2,4}&quot; /&gt;
        '''  &lt;Regex name=&quot;BitmapFile&quot; forecol=&quot;DarkRed&quot; pattern=&quot;file\((?=\s*\d+\s*\-\s*\d+\s*\):)|(?&amp;lt;=file\(\s*\d+\s*\-\s*\d+\s*)\):&quot; /&gt;
        '''  &lt;Regex name=&quot;FileNumbers&quot; forecol=&quot;Fuchsia&quot; pattern=&quot;(?&amp;lt;=file\()\s*\d+\s*\-\s*\d+\s*(?=\):)&quot; /&gt;        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property syntax_special() As String
            Get
                Return ResourceManager.GetString("syntax_special", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;frame&gt; 0 in_the_sky
        '''   pic: 0  state: 2000  wait: 3  next: 1  dvx: 0  dvy: 0  centerx: 29  centery: 56
        '''   itr:
        '''      kind: 0  x: 6  y: 9  w: 44  h: 46  dvx: 5  dvy: -7  fall: 70  vrest: 17  bdefend: 30  injury: 60  
        '''   itr_end:
        '''   bdy:
        '''      kind: 0  x: 6  y: 9  w: 44  h: 46
        '''   bdy_end:
        '''&lt;frame_end&gt;
        '''
        '''&lt;frame&gt; 1 in_the_sky
        '''   pic: 1  state: 2000  wait: 2  next: 2  dvx: 0  dvy: 0  centerx: 29  centery: 56
        '''   itr:
        '''      kind: 0  x: 6  y: 9  w: 44  h: 46  dvx: 5  dvy: -7  fall: 70  vrest: 17  bdefen [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property weapon_heavy() As String
            Get
                Return ResourceManager.GetString("weapon_heavy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;frame&gt; 20 on_hand
        '''   pic: 20  state: 1001  wait: 0  next: 0  dvx: 0  dvy: 0  dvz: 0  centerx: 24  centery: 40  hit_a: 0  hit_d: 0  hit_j: 0
        '''   wpoint:
        '''      kind: 2  x: 24  y: 40  weaponact: 0  attacking: 0  cover: 0  dvx: 0  dvy: 0  dvz: 0 
        '''   wpoint_end:
        '''   itr:
        '''      kind: 5  x: 18  y: 4  w: 12  h: 50  fall: 20  bdefend: 16  injury: 789  
        '''   itr_end:
        '''&lt;frame_end&gt;
        '''
        '''&lt;frame&gt; 21 on_hand
        '''   pic: 21  state: 1001  wait: 0  next: 0  dvx: 0  dvy: 0  dvz: 0  centerx: 24  centery: 40  hit_a: 0  hit_d: 0  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property weapon_normal() As String
            Get
                Return ResourceManager.GetString("weapon_normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
